/**
 * Middleware methods that are `@job` on TrueNAS.
 *
 * A `@job` method returns a JOB ID — a bare number — immediately, not a result.
 * A handler that returns it unchanged reports the *enqueue* as the outcome, so
 * a FAILED operation reads as success. That defect was found and fixed for the
 * filesystem handlers in v1.1.1; the wider sweep was deferred and, when finally
 * run on 2026-09-25, found 36 more call sites.
 *
 * This list is the one thing here that cannot be re-derived offline — job-ness
 * is a property of the running middleware, not of this repo. It was captured
 * from `core.get_methods` on TrueNAS **26.0.0-BETA.1** (2026-09-24): 101 of the
 * 781 published methods carry the `@job` flag.
 *
 * ⚠ It is therefore a recorded fact, and it can decay — a future TrueNAS may
 * make a method a job, or stop. `src/__tests__/job-wrapping.test.ts` gates the
 * half that IS derivable: that every call to a method named here is wrapped.
 * Re-capture this list when targeting a new TrueNAS major.
 */
export const JOB_METHODS: ReadonlySet<string> = new Set([
  "app.convert_to_custom",
  "app.create",
  "app.delete",
  "app.image.pull",
  "app.pull_images",
  "app.redeploy",
  "app.rollback",
  "app.start",
  "app.stop",
  "app.update",
  "app.upgrade",
  "app.upgrade_bulk",
  "audit.download_report",
  "audit.export",
  "boot.attach",
  "boot.replace",
  "boot.scrub",
  "catalog.sync",
  "certificate.create",
  "certificate.delete",
  "certificate.update",
  "cloud_backup.delete_snapshot",
  "cloud_backup.restore",
  "cloud_backup.sync",
  "cloudsync.sync",
  "cloudsync.sync_onetime",
  "config.reset",
  "config.save",
  "config.upload",
  "container.create",
  "container.migrate",
  "container.stop",
  "core.bulk",
  "core.job_wait",
  "cronjob.run",
  "directoryservices.cache_refresh",
  "directoryservices.leave",
  "directoryservices.sync_keytab",
  "directoryservices.update",
  "disk.wipe",
  "docker.backup",
  "docker.backup_to_pool",
  "docker.restore_backup",
  "docker.update",
  "failover.reboot.other_node",
  "filesystem.chown",
  "filesystem.get",
  "filesystem.put",
  "filesystem.setacl",
  "filesystem.setperm",
  "idmap.clear_idmap_cache",
  "ipmi.sel.clear",
  "ipmi.sel.elist",
  "ipmi.sel.info",
  "kmip.update",
  "mail.send",
  "pool.attach",
  "pool.create",
  "pool.dataset.change_key",
  "pool.dataset.encryption_summary",
  "pool.dataset.export_key",
  "pool.dataset.export_keys",
  "pool.dataset.export_keys_for_replication",
  "pool.dataset.lock",
  "pool.dataset.unlock",
  "pool.ddt_prefetch",
  "pool.ddt_prune",
  "pool.expand",
  "pool.export",
  "pool.import_find",
  "pool.import_pool",
  "pool.prefetch",
  "pool.reimport",
  "pool.remove",
  "pool.replace",
  "pool.scrub",
  "pool.scrub.scrub",
  "pool.update",
  "replication.run",
  "replication.run_onetime",
  "rsynctask.run",
  "service.control",
  "support.attach_ticket",
  "support.new_ticket",
  "systemdataset.update",
  "system.debug",
  "system.reboot",
  "system.security.update",
  "system.shutdown",
  "truenas.set_production",
  "tunable.create",
  "tunable.delete",
  "tunable.update",
  "update.download",
  "update.file",
  "update.manual",
  "update.run",
  "vm.device.convert",
  "vm.log_file_download",
  "vm.restart",
  "vm.stop",
]);
